Feat/product page
ikorsar/fake-burrberry-frontend pull request #1
Opened 2017-07-31 16:57 UTC by ikorsar

2017-08-01 09:02 UTC, evgenyrodionov commented
В коммитах не делай тире, это же список в телеграфе)

2017-08-01 09:03 UTC, evgenyrodionov commented
https://rawgit.com/ikorsar/fake-burrberry-frontend/feat/product-page/index.html

2017-08-01 09:06 UTC, evgenyrodionov commented
В макете было 18.5, я поправил до 16, поправь у себя

![image](https://user-images.githubusercontent.com/775692/28817754-e041ae46-76b1-11e7-9d2b-a1d34e0284e4.png)

2017-08-01 09:07 UTC, evgenyrodionov commented
Тут начало ехать

![image](https://user-images.githubusercontent.com/775692/28817787-f759e77e-76b1-11e7-8715-e371de968a69.png)

2017-08-01 09:09 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28817814-0bc23e5a-76b2-11e7-91f1-075853140563.png)

2017-08-01 09:10 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28817928-626c6c4e-76b2-11e7-8092-b6c4a0c75286.png)
![image](https://user-images.githubusercontent.com/775692/28817949-6fd735ee-76b2-11e7-9aa2-fbe66daedc85.png)

2017-08-01 09:12 UTC, imevro requested changes
По дизайну поправь

По кодстайлу в целом норм, сам код не смотрел

2017-08-01 17:33 UTC, evgenyrodionov commented
!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!

https://github.com/ikorsar/fake-burrberry-frontend/pull/1#issuecomment-319312593

!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!

2017-08-01 17:44 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28838740-f19e4f12-76f9-11e7-9c88-77f12c05ada6.png)
![image](https://user-images.githubusercontent.com/775692/28838755-fee2b726-76f9-11e7-9cd4-a3caf4fcfe47.png)
![image](https://user-images.githubusercontent.com/775692/28838779-0e1727fe-76fa-11e7-8e27-1b4af08ea080.png)

2017-08-01 17:44 UTC, imevro requested changes
фикси дизайн

2017-08-02 10:01 UTC, evgenyrodionov commented
На 1 пкс едет заголовок если выравнивать относительно текста
![image](https://user-images.githubusercontent.com/775692/28868572-8d66a240-7782-11e7-8ecd-54e6853e8881.png)
![image](https://user-images.githubusercontent.com/775692/28868598-a512b6ae-7782-11e7-8169-8ff3ef166c7f.png)

2017-08-02 10:01 UTC, imevro requested changes
↑

2017-08-02 17:43 UTC, evgenyrodionov commented
Мыльцо слегка

![image](https://user-images.githubusercontent.com/775692/28886732-26590782-77c3-11e7-9114-8f3942d95562.png)

2017-08-02 17:48 UTC, imevro requested changes
нейминг плох, зато с общими стилями красиво управляешьсф

2017-08-02 17:48 UTC, evgenyrodionov commented on index.html
> +    <img class="logo-img" src="media/images/logo.svg" alt="Burberry Logo">
page-header > logo-img? что с неймингом?

2017-08-02 17:48 UTC, evgenyrodionov commented on index.html
> +  <link rel="stylesheet" type="text/css" href="media/styles/styles.css">
`type="text/css"` давно депрекейтед + у тебя сверху его нет, а тут почему-то есть, где согласованность

2017-08-02 17:48 UTC, evgenyrodionov commented on index.html
> +  <meta name='viewport' content='width=device-width'>
тут одинарные кавычки, везде двойные, втф

2017-08-02 17:48 UTC, evgenyrodionov commented on index.html
> +      <h1 class="product-title-content">Long Cotton Gabardine Car Coat</h1>
зачем тебе тут див?

2017-08-02 17:48 UTC, evgenyrodionov commented on index.html
> +      <div class="product-photo">
product-gallery > product-photo? WTF?

2017-08-02 17:48 UTC, evgenyrodionov commented on index.html
> +      <p class="product-details-partnumber">Item 39428531</p>
Это артикул

2017-08-02 17:48 UTC, evgenyrodionov commented on index.html
> +        <span class="radio-button">
product-colors, product-colors-buttons, RADIO-BUTTON

2017-08-02 17:48 UTC, evgenyrodionov commented on index.html
> +        <span class="radio-button">
зачем тут вообще радиобаттоны к слову

2017-08-02 17:48 UTC, evgenyrodionov commented on index.html
> +      <button class="product-size-help-button" type="button">Need size help?</button>
это почему не btn?

2017-08-02 17:48 UTC, evgenyrodionov commented on index.html
> +          <li class="dropdown-list-item">Outer: 100% cotton</li>
с сервера не приходит верстка с классами

2017-08-02 17:48 UTC, evgenyrodionov commented on index.html
> +      <h2 class="section-title">We recommend</h2>
product-section > SECTION-TITLE

2017-08-02 17:48 UTC, evgenyrodionov commented on index.html
> +    <button class="service-text-button" type="button">Shipping country: Russian Federation</button>
page-footer > SERVICE-TEXT-BUTTON

2017-08-02 17:48 UTC, evgenyrodionov commented on index.html
> +      <li class="help-links-item">
ul li тут зачем вообще

2017-08-02 17:48 UTC, evgenyrodionov commented on media/styles/styles.css
> +*,
не занимайся работой нормалайза

2017-08-02 17:48 UTC, evgenyrodionov commented on media/styles/styles.css
> +  box-sizing: border-box;
не трогай

2017-08-02 17:48 UTC, evgenyrodionov commented on media/styles/styles.css
> +  display: inline-block;
с хуя ли

2017-08-02 17:48 UTC, evgenyrodionov commented on media/styles/styles.css
> +  font: 400 1rem/1.19 'Lora', Helvetica, Arial, serif;
распиши по свойствам, эту портянку читать сложно

2017-08-02 17:48 UTC, evgenyrodionov commented on media/styles/styles.css
> +/* header styles stop */
end, не stop

2017-08-03 11:51 UTC, imevro requested changes

2017-08-03 11:51 UTC, evgenyrodionov commented on product-card.html
> +    <img class="page-header-logo" src="media/images/logo.svg" alt="Burberry Logo">
добавь ссылку

2017-08-03 11:51 UTC, evgenyrodionov commented on index.html
> +      <p class="product-details-partnumber">Item 39428531</p>
ЭТО АРТИКУЛ

2017-08-03 11:52 UTC, evgenyrodionov commented
и делай планшет

2017-08-03 19:23 UTC, evgenyrodionov commented
Тупость с картинками, она должна быть к левому краю
![image](https://user-images.githubusercontent.com/775692/28939517-44f8fa76-789a-11e7-809e-118a50492cd5.png)

Тоже так себе
![image](https://user-images.githubusercontent.com/775692/28939502-375c1146-789a-11e7-8f1a-dda8c4e19c38.png)

2017-08-04 09:50 UTC, evgenyrodionov commented
Проверю в 8

2017-08-04 13:43 UTC, evgenyrodionov commented
Очень приятно выглядит

2017-08-04 13:45 UTC, imevro requested changes
читай телеграф

2017-08-04 13:45 UTC, evgenyrodionov commented on media/styles/product-card.css
> +  margin: 0 -.5rem;
отрицательные марджины зло

2017-08-04 13:45 UTC, evgenyrodionov commented on media/styles/product-card.css
> +  margin: 0 -.5rem;
unless you can say for what

2017-08-04 13:45 UTC, evgenyrodionov commented on media/styles/product-card.css
> +  .dropdown-delivery-options h5 {
стили по тегам зло

2017-08-04 13:45 UTC, evgenyrodionov commented on product-card.html
> +            <ul class="page-footer-nav-list">
Списки не для списков

2017-08-04 19:07 UTC, imevro approved these changes

2017-08-04 19:07 UTC, evgenyrodionov commented
Делай планшет

2017-08-04 19:54 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28984675-cde0fb18-7967-11e7-9adf-5f976098084b.png)

2017-08-05 09:49 UTC, imevro requested changes

2017-08-05 09:49 UTC, evgenyrodionov commented on media/styles/product-card.css
> +  .product-section-seo {
что это

2017-08-05 09:49 UTC, evgenyrodionov commented on media/styles/styles.css
> +video {
этим всем занимается нормалайз, ты-то куда лезешь

2017-08-05 09:49 UTC, evgenyrodionov commented on product-card.html
> +            <div class="product-gallery-item">
зачем тут лишний див?

2017-08-05 09:49 UTC, evgenyrodionov commented on product-card.html
> +        <ul class="product-recomendation-list">
списки только для списков внутри текста, не для разметки

2017-08-05 09:49 UTC, evgenyrodionov commented on product-card.html
> +        <ul class="product-recomendation-list">
и ваще тут сетка

2017-08-05 18:41 UTC, imevro requested changes

2017-08-05 18:41 UTC, evgenyrodionov commented on media/styles/styles.css
> +  line-height: 1.063rem;
что за меджик намбер?

2017-08-05 18:41 UTC, evgenyrodionov commented on product-card.html
> +    </div>
не понимаю к чему относится этот див

2017-08-06 08:50 UTC, imevro requested changes
как исправишь — мердж через сквош (кнопка такая)

2017-08-06 08:50 UTC, evgenyrodionov commented on product-card.html
>              <p class="page-footer-nav-title">Customer service</p>
это же заголовок

2017-08-06 10:42 UTC, merged