Add react and split to components
ikorsar/fake-burrberry-frontend pull request #2
Opened 2017-08-08 16:59 UTC by ikorsar

2017-08-09 09:53 UTC, imevro requested changes
- Тайтлы через react-helmet
- Нормальные manifest.json и package.json
- Поставьте prettier
- Функции — тупым компонентам, классы — рабочим
- Избавляйтесь от избыточных префиксов
- Архитектура должна быть про продукт

2017-08-09 09:53 UTC, evgenyrodionov commented on src/Product/ProductCardRecommended/ProductCardRecommended.js
> +  <div className="col-xs-6 col-md-3">
А если я захочу использовать этот файл в другом месте с другой сеткой? вынеси за пределы

2017-08-09 09:53 UTC, evgenyrodionov commented on src/Product/ProductDetails/ProductDetails.js
> +          <Button label="Select a size" secondary/>
есть пропс чилдрен

2017-08-09 09:53 UTC, evgenyrodionov commented on src/index.js
> +import "./styles/flexboxgrid.css";
почему не через нпм? втф?

2017-08-10 10:27 UTC, imevro requested changes
Читай телеграф, ты собрал почти все ошибки оттуда

2017-08-10 18:06 UTC, imevro requested changes

2017-08-10 18:06 UTC, evgenyrodionov commented on src/App.jsx
> +    <Helmet defaultTitle="Burberry" titleTemplate="%s | Burberry" />
вот за это красава

2017-08-10 18:06 UTC, evgenyrodionov commented on src/App.jsx
> +    <PageFooter />
зачем все эти префиксы пейдж?

2017-08-10 18:06 UTC, evgenyrodionov commented on src/Product/ButtonColor/index.jsx
> +        bgColor={this.props.bgColorValue}
label/value

2017-08-10 18:06 UTC, evgenyrodionov commented on src/Product/Delivery/Accordion/index.jsx
> +class AccordionDelivery extends Accordion {
опять же как в чате писал — в мусорку ООП

2017-08-10 18:06 UTC, evgenyrodionov commented on src/Product/Details/index.jsx
> +      <Price priceValue="110 000" priceCurrency="руб" />
почему передаешь цену строкой?

2017-08-10 18:06 UTC, evgenyrodionov commented on src/Product/index.jsx
> +      <Title label="Long Cotton Gabardine Car Coat" />
почему не children? зачем label?

2017-08-10 18:06 UTC, evgenyrodionov commented on src/components/Footer/index.jsx
> +    <HelpLink href="#" title="Find out more and contact us" />
и тут тоже зачем сломал? чилдрены есть

2017-08-11 09:11 UTC, ikorsar commented
Дестоп пока не смотри

2017-08-11 11:10 UTC, evgenyrodionov commented
Я напоминаю что не смотрю бракованные ПРы

2017-08-11 18:51 UTC, imevro requested changes

2017-08-11 18:51 UTC, evgenyrodionov commented on src/App.jsx
> +import Header from './components/Header/';
зачем компонентс?

2017-08-11 18:51 UTC, evgenyrodionov commented on src/App.jsx
> +import Footer from './components/Footer/';
не понимаю зачем ты в конце хранишь слеш

2017-08-11 18:51 UTC, evgenyrodionov commented on src/Product/Description/index.jsx
> +import { Desktop, Mobile, TabletAndMore } from '../../components/Breakpoints';
ужасный нейминг — несогласованный с фбг раз, неконсистентный друг с другом два (почему TabletAndMore, но при этом DESKTOP)

2017-08-11 18:51 UTC, evgenyrodionov commented on src/Product/Details/PartNumber/index.jsx
> +    Item {props.partNumber}
зачем заводить этот компонент-прокладку? что тебе мешает использовать стайлед-компонент где тебе нужно?

2017-08-11 18:51 UTC, evgenyrodionov commented on src/Product/Details/PartNumber/index.jsx
> +    Item {props.partNumber}
и не заводи директорию ради одного файла индекс.джс в ней

2017-08-11 18:51 UTC, evgenyrodionov commented on src/Product/Details/index.jsx
> +import { Choose, Value } from '../../components/ChooseVariant';
Choose? Value? wtf?

2017-08-11 18:51 UTC, evgenyrodionov commented on src/Product/Details/index.jsx
> +            <Value>Honey</Value>
это обычный текст, что за чоозе валуе

2017-08-11 18:51 UTC, evgenyrodionov commented on src/Product/Details/index.jsx
> +        <ButtonContainer>
слишком много контейнеров, тейк ит изи

2017-08-11 18:51 UTC, evgenyrodionov commented on src/Product/Details/index.jsx
> +        <DesktopLess>
Без max-width

2017-08-12 12:02 UTC, imevro requested changes

2017-08-12 12:02 UTC, evgenyrodionov commented on src/Footer/Buttons.jsx
> +    <Button type="button" label="Shipping country: Russian Federation" />
зачем лейбл? помести контент между открывающим и закрывающим тегом, это называется чилдреном

2017-08-12 12:02 UTC, evgenyrodionov commented on src/Footer/index.jsx
> +import Nav from './Nav/index';
зачем?

2017-08-12 12:02 UTC, evgenyrodionov commented on src/Product/Description/Img.jsx
> +export default props => <Img src={`/files/${props.photoName}.jpg`} alt={props.alt} />;
зачем эта прокладка?

2017-08-12 12:02 UTC, evgenyrodionov commented on src/Product/Description/Img.jsx
> +export default props => <Img src={`/files/${props.photoName}.jpg`} alt={props.alt} />;
экспорти сразу ск

2017-08-12 12:02 UTC, evgenyrodionov commented on src/Product/Description/index.jsx
> +const MediaQuery = require('react-responsive');
почему не импортом?

2017-08-12 12:02 UTC, evgenyrodionov commented on src/Product/Details/Colors/index.jsx
> +      {' '}Colour: <strong>Honey</strong>
а зачем вот этот пробел?

2017-08-12 12:02 UTC, evgenyrodionov commented on src/Product/Details/index.jsx
> +const MediaQuery = require('react-responsive');
ты выше импортнул Responsive из реакт-респонсив, зачем тебе теперь тот же импорт под именем медиквери?

2017-08-12 18:25 UTC, imevro requested changes

2017-08-12 18:25 UTC, evgenyrodionov commented on src/Footer/Nav/Link.jsx
> +    {props.children}
а зачем эта прокладка

2017-08-12 18:25 UTC, evgenyrodionov commented on src/Product/Description.jsx
> +            <Title>Description</Title>
что-то ты очень тупо придумал с дублированием всего контента

2017-08-12 18:25 UTC, evgenyrodionov commented on src/Product/Details/Colors/index.jsx
> +    <ColorsContainer>
ты и так в колорс, зачем тебе столько префиксов

2017-08-12 18:25 UTC, evgenyrodionov commented on src/Product/Info.jsx
> +      <MediaQuery maxWidth={991}>
мы не оперируем max-ами

2017-08-13 11:36 UTC, imevro approved these changes

2017-08-13 11:36 UTC, merged