Add products list
ikorsar/fake-burrberry-frontend pull request #5
Opened 2017-08-17 14:17 UTC by ikorsar

2017-08-17 16:34 UTC, ikorsar commented
build and deploy on https://build-kpfzexurpy.now.sh/

2017-08-17 20:38 UTC, evgenyrodionov commented
Чё пикчи такие артефактные

![image](https://user-images.githubusercontent.com/775692/29432674-23724a86-83a5-11e7-82b0-87c3fd9b17a1.png)

2017-08-17 20:38 UTC, evgenyrodionov commented
Пикча артефактная, плюс полезли следующие за ней

![image](https://user-images.githubusercontent.com/775692/29432689-34a3cc08-83a5-11e7-9ca8-b548e2b2c02a.png)

2017-08-17 20:39 UTC, evgenyrodionov commented
При клике на сердечко в карточке товара меня перекидывает на страницу товара — не должно

2017-08-17 20:39 UTC, evgenyrodionov commented
Тут попидорило + проставь ссылки нормальные, а не продакт1 где я и так нахожусь

![image](https://user-images.githubusercontent.com/775692/29432710-549da5ba-83a5-11e7-92c7-b55ed448ad9e.png)

2017-08-17 20:40 UTC, evgenyrodionov commented
Откуда цены взялись RUB110,000, если было 110 000₽?

2017-08-17 20:41 UTC, evgenyrodionov commented
Оч вплотную описание

![image](https://user-images.githubusercontent.com/775692/29432766-7e7afcd4-83a5-11e7-92e5-f42eb2fbdb6f.png)

2017-08-17 20:41 UTC, evgenyrodionov commented
Всё остальное вроде ок, красиво выглядит

2017-08-17 20:45 UTC, imevro requested changes

2017-08-17 20:45 UTC, evgenyrodionov commented on src/Footer/HelpLink.jsx
> +export default function HelpLinkExport(props) {
тупой нейминг "export"

2017-08-17 20:45 UTC, evgenyrodionov commented on src/Header/index.jsx
> +  width: 166px;
а зачем ширину задавать? достаточно высоту

2017-08-17 20:45 UTC, evgenyrodionov commented on src/Header/index.jsx
> +        <Arrow src={arrow} />
ну хуй знает оправдано ли засорять таким разметку

2017-08-17 20:45 UTC, evgenyrodionov commented on src/Product/Card/index.jsx
> +  (<CardStyled to={props.link} title={props.title}>
to={link}? где согласованность?

2017-08-17 20:45 UTC, evgenyrodionov commented on src/Product/Card/index.jsx
> +    <Photo src={props.photoName} alt={props.title} />
src={photoName}? wtf?

2017-08-17 20:45 UTC, evgenyrodionov commented on src/Product/Card/index.jsx
> +              <Color>{props.colourQuantity} colours</Color>
1 colors

2017-08-17 20:45 UTC, evgenyrodionov commented on src/Product/List/SubCategory.jsx
> +          fullCard
что за костыльный проп

2017-08-17 20:45 UTC, evgenyrodionov commented on src/Product/List/index.jsx
> +    this.state = {};
и зачем тут стейт

2017-08-17 20:45 UTC, evgenyrodionov commented on src/App.jsx
> +              <Route exact path="/products" component={List} />
ок, вопрос — у тебя в меню есть men, women, children. Как это тут отражено?

2017-08-17 20:45 UTC, evgenyrodionov commented on src/App.jsx
> +              <Route exact path="/products" component={List} />
а также men/women/children делится на аксессуары, одежду, обувь, етц. think about it. думай о бизнесе.

2017-08-18 08:58 UTC, ikorsar commented
new link https://build-eemxohopbr.now.sh

2017-08-18 08:59 UTC, ikorsar commented
пока не разобрался с качеством картинок. интернет очень плохой. к вечеру разберусь.

2017-08-18 08:59 UTC, ikorsar commented
и клик на сердечке не поправил.

2017-08-18 17:03 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/29469272-32d3fe1a-8450-11e7-9f0b-2a72f243cdbc.png)
![image](https://user-images.githubusercontent.com/775692/29469280-3b55212c-8450-11e7-9fe6-2fe3ea94d86a.png)
![image](https://user-images.githubusercontent.com/775692/29469300-494a53b0-8450-11e7-8c5d-dcf4643a1449.png)
![image](https://user-images.githubusercontent.com/775692/29469308-520f4532-8450-11e7-96bb-418c709c9022.png)

2017-08-18 19:46 UTC, ikorsar commented
карточки товаров в макете не по сетке 
![image](https://user-images.githubusercontent.com/8079585/29474355-0812a528-8464-11e7-9f68-c53641d6d6c1.png)

 у меня они все в колоночках, как надо. 

по обсуждению в телеграме у картинок надо ставить width:100% (как у меня и было), но при этом высота их может отличаться от высоты в макете.
![image](https://user-images.githubusercontent.com/8079585/29474991-9e2c627c-8466-11e7-97b9-0b714e94cb9e.png)

из-за этих двух пикселей в макете при наложении все что ниже начинает расползаться.
![image](https://user-images.githubusercontent.com/8079585/29473955-69353b10-8462-11e7-8d4d-49d745ad3bdf.png)

тут начинает ползти из-за неправильного указания бордера в макете 
![image](https://user-images.githubusercontent.com/8079585/29474128-08038b5c-8463-11e7-96ae-385146978367.png) 
если в скетче исправить inside на outside то будет норм
![image](https://user-images.githubusercontent.com/8079585/29474200-6307458e-8463-11e7-9383-08d57703a1e4.png)

сердечки в макете для планшетов
![image](https://user-images.githubusercontent.com/8079585/29474516-b394f892-8464-11e7-834e-ef59a4674321.png)

тут странный отступ в 65 пикселей, я сделал чтобы было 64 
![image](https://user-images.githubusercontent.com/8079585/29474591-02f0ec16-8465-11e7-9985-ceb491e9fd02.png)

отступ в 5 пикселей, у меня 4
![image](https://user-images.githubusercontent.com/8079585/29474770-c65a68f8-8465-11e7-8e10-49f977a8edcb.png)

и там же отступ в 15 пикселей. он явно тут лишний, я его не ставил
![image](https://user-images.githubusercontent.com/8079585/29474857-1e899774-8466-11e7-96cb-c7d83dd0bdcc.png)

2017-08-18 22:32 UTC, evgenyrodionov commented
пиздец)

2017-08-18 22:53 UTC, evgenyrodionov commented
Задеплой?

2017-08-19 07:11 UTC, ikorsar commented
new link https://build-vkierpndkj.now.sh

2017-08-19 07:23 UTC, ikorsar commented
new link https://build-fwcxqpenmn.now.sh

2017-08-19 07:40 UTC, ikorsar commented
new link https://build-eehwfrpwed.now.sh

2017-08-19 09:50 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/29485583-d1fa3856-84dc-11e7-8ae3-57e5b1dc52dd.png)

2017-08-19 09:51 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/29485587-ee215fb4-84dc-11e7-9e5a-8b3db0d5bd32.png)

Отступы у цены не те плюс цвет шрифта плюс формат, что за RUB
![image](https://user-images.githubusercontent.com/775692/29485593-0335edf2-84dd-11e7-80bd-60c4c2056506.png)
![image](https://user-images.githubusercontent.com/775692/29485595-10124778-84dd-11e7-81c2-95e1d8013842.png)

2017-08-19 09:52 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/29485608-298c050e-84dd-11e7-8af0-6509aed0e61d.png)
![image](https://user-images.githubusercontent.com/775692/29485612-32b68212-84dd-11e7-8de1-c0e4c8f8e5f2.png)

2017-08-19 13:25 UTC, ikorsar commented
если в верстке поставить фиксированную высоту в 48 пикселей кнопке "View 9 more" и отступ в 5 пикселей для "Available Colors" то получается как на макете
![image](https://user-images.githubusercontent.com/8079585/29486831-ef2a31d6-84f7-11e7-92f2-9a50755e4ce7.png)

но это неверно и поэтому у меня нет высоты у кнопки, а есть отступы внутри. и отступ от "Available Colors" 4 пикселя, мне кажется что этот отступ правильнее. из-за этого получается вот так:
![image](https://user-images.githubusercontent.com/8079585/29486853-5168709c-84f8-11e7-8ffc-d7d45b0aad81.png)

2017-08-19 13:31 UTC, ikorsar commented
link https://build-wrhlznajpw.now.sh

2017-08-19 19:04 UTC, evgenyrodionov commented
А почему на десктопе скроллится

![image](https://user-images.githubusercontent.com/775692/29489455-4b95c3ea-852a-11e7-90f8-a10d115ad0f9.png)

2017-08-19 19:21 UTC, imevro requested changes

2017-08-19 19:21 UTC, evgenyrodionov commented on src/Footer/Buttons.jsx
> +   {
а зачем тут скобки

2017-08-19 19:21 UTC, evgenyrodionov commented on src/Product/List/CategoryHeader/Filters.jsx
> +import arrow from '../../../Header/arrow.svg';
тебя не напрягает что тебе за арроу приходится ходить в хедер?

2017-08-19 19:21 UTC, evgenyrodionov commented on src/Product/Show/Recommended.jsx
> +import Card from '../Card/index';
зачем тут индекс?

2017-08-19 19:21 UTC, evgenyrodionov commented on src/Product/Card/index.jsx
> +        <LinkStyled to={`/products/${props.category}/${props.subcategory}/${props.to}`}>
вот ты дважды конструируешь ссылку, хотя мог бы передавать просто один проп `to` где она бы уже была

2017-08-19 23:24 UTC, ikorsar commented
link https://build-kuvlndwari.now.sh

2017-08-20 09:30 UTC, imevro approved these changes

2017-08-20 09:30 UTC, merged