Add interactive for pages
ikorsar/fake-burrberry-frontend pull request #7
Opened 2017-08-28 16:30 UTC by ikorsar

2017-08-28 17:19 UTC, ikorsar commented
Link https://build-erbclgbyng.now.sh/products/men/
проверять: лайк, фильтры (пока без затемнения списка) и меню (пока без селектов и подменю)

2017-08-28 17:42 UTC, evgenyrodionov commented
"пока" и "пока" это несделанные задания, мне нечего проверять

2017-08-28 17:43 UTC, imevro requested changes
всё остальное несделанное не проверял, лайк проверил

2017-08-28 17:43 UTC, evgenyrodionov commented on src/Product/Card/Fav.jsx
> +        <Svg width="16px" height="15px" viewBox="0 0 16 15" xmlns="http://www.w3.org/2000/svg">
вынеси в отдельный компонент

2017-08-28 17:43 UTC, evgenyrodionov commented on src/Product/Card/Fav.jsx
> +        className={this.state.isActive ? 'is-active' : null}
мы не используем классы, потому что у нас есть СК с нормальной работой с пропами

2017-08-28 17:43 UTC, evgenyrodionov commented on src/Product/Card/Fav.jsx
> +    this.eventHandler = this.eventHandler.bind(this);
плохой нейминг — какого эвента это хендлер?

2017-08-29 16:52 UTC, ikorsar commented
link https://build-rlgyarnukd.now.sh
можно смотреть: лайк, фильтры, выбор размера и цвета, выбор страны и языка в хедере и футере и мобильное меню

2017-08-29 19:45 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/29840751-baf1e032-8d0b-11e7-9975-602fbcbfaefe.png)

2017-08-29 19:48 UTC, evgenyrodionov commented
А чё такое мелкое?

![image](https://user-images.githubusercontent.com/775692/29840872-21bbffa0-8d0c-11e7-8c83-47dbacb24f53.png)

2017-08-29 19:50 UTC, evgenyrodionov commented
А почему второй шаг в меню не сделан? Подкатегории men/women  етц?

2017-08-29 20:05 UTC, imevro requested changes

2017-08-29 20:05 UTC, evgenyrodionov commented on package.json
> +    "babel-eslint": "^7.2.3",
в девдепс

2017-08-29 20:05 UTC, evgenyrodionov commented on src/App.jsx
> +                <Header menuOpen={this.handleClick} />
menuOpen выглядит как булеан значение

2017-08-29 20:05 UTC, imevro commented on src/Footer/Buttons.jsx
> +    const handleSelect = (e) => {
почему это в рендере? стейт нельзя из рендера обновлять

2017-08-29 20:05 UTC, evgenyrodionov commented on src/Product/Card/index.jsx
> +        {props.label !== ' ' && <Label label={props.label}>{props.label}</Label>}
.trim()

2017-08-29 20:05 UTC, evgenyrodionov commented on src/Product/List/Filter.jsx
> +    if (on === false && on === this.state.isOpened) return;
нулевые рётерны плохо

2017-08-29 20:05 UTC, imevro commented on src/Product/List/index.jsx
> +    props.open &&
open? а в самом классе у тебя isOpened. приведи к одному виду

2017-08-29 20:05 UTC, imevro commented on src/Product/List/index.jsx
> +                      Content content content content content content content<br />
у каждого дропдауна будет свой контент, поэтому мап здесь не очень подходит

2017-08-29 20:05 UTC, evgenyrodionov commented on src/Product/Show/Details/Colors.jsx
> +          className={active ? 'is-active' : null}
а зачем классы?

2017-08-29 20:05 UTC, evgenyrodionov commented on src/Product/Show/Details/Colors.jsx
> +          className={active ? 'is-active' : null}
у тебя в ск есть возможность работать с пропами, передай просто isActive и всё

2017-08-29 20:05 UTC, evgenyrodionov commented on src/components/Heart.jsx
> +  state = {};
а зачем тут стейт

2017-08-29 20:05 UTC, evgenyrodionov commented on src/components/Heart.jsx
> +        active={this.props.active}
лучше передавай сразу филл

2017-08-30 16:15 UTC, ikorsar commented
link: https://build-dulvjodnje.now.sh
все поправил. подменю в процессе пока

2017-08-30 19:08 UTC, imevro requested changes

2017-08-30 19:08 UTC, evgenyrodionov commented on src/App.jsx
> +                <Header setMenuOpen={this.handleClick} />
лучше handleChange или handleMenuOpen

2017-08-30 19:08 UTC, evgenyrodionov commented on src/Product/List/Filter.jsx
> +        () => ({ isOpened: !this.state.isOpened }),
https://github.com/mlshv/fake-burberry-frontend/pull/10#discussion_r136157858

2017-08-30 19:08 UTC, evgenyrodionov commented on src/Product/List/index.jsx
> +      open: !this.state.open,
isOpened?

2017-08-30 19:08 UTC, evgenyrodionov commented on src/components/Heart.jsx
> +  fill: ${props => (props.fill ? '#171717' : '#fff')};
зачем передавать булеан? почему ты не можешь передавать сразу значение которое нужно подставить?

2017-08-30 19:08 UTC, evgenyrodionov commented on src/components/Heart.jsx
> +  fill: ${props => (props.fill ? '#171717' : '#fff')};
тебе нужно будет переиспользовать этот компонент и красить в красный в другом месте (личный кабинет, например). что делать будешь?

2017-08-31 08:37 UTC, ikorsar commented
link: https://build-wizwcyekyw.now.sh
все поправил. добавил подменю

2017-08-31 12:37 UTC, imevro requested changes

2017-08-31 12:37 UTC, imevro commented on src/MobileMenu/Nav.jsx
> +const Category = styled.a`
это кнопка, не ссылка

2017-08-31 12:37 UTC, imevro commented on src/MobileMenu/index.jsx
> +      submenuOpen: !this.state.submenuOpen,
https://medium.com/@shopsifter/using-a-function-in-setstate-instead-of-an-object-1f5cfd6e55d1

2017-08-31 12:37 UTC, imevro commented on src/MobileMenu/Submenu.jsx
> +      <Title>Men</Title>
разграничь хотя бы базово на уровне тайтлов разные категории

2017-08-31 23:03 UTC, ikorsar commented
https://build-lubergpbrb.now.sh

2017-09-01 11:10 UTC, imevro approved these changes

2017-09-01 11:10 UTC, evgenyrodionov commented
Жди апи)

2017-09-01 11:10 UTC, merged